name: DevOps%20Practice/CodeBase_(2)
on:
  push:
    branches:
    - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - run: npm install
    - run: npm run build
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: drop
        path: build
